/**
 * white-label.config.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * All client-specific settings live here. To create a white-label instance
 * for a new solar dealer, duplicate this repo, change values in this ONE file,
 * and redeploy.
 */

export const WHITE_LABEL = {
    // ── Brand Identity ──────────────────────────────────────────────────────
    companyName: "SeptiVolt",
    tagline: "AI Solar Sales Training Operating System",
    supportEmail: "support@septivolt.com",

    // ── Visual Theming ───────────────────────────────────────────────────────
    // Used for CSS variable injection (see layout.tsx / globals.css)
    colors: {
        primary: "#F97316",   // Solar Orange — buttons, accents
        primaryDim: "#EA580C",   // Orange dim — hover states
        surface: "#121212",   // Slate Base — main bg
        card: "#1A1A1A",   // Charcoal panel — card bg
        text: "#94A3B8",   // Silver text — primary text
    },

    // ── Logo ─────────────────────────────────────────────────────────────────
    // Place logo file at /public/brand/logo.png (or .svg)
    // Set to null to show companyName text instead.
    logoPath: null as string | null,

    // ── Presentation Mode ────────────────────────────────────────────────────
    // "local_pdf"    → serve PDFs from /public/slides/ (current setup)
    // "google_slides" → embed Google Slides iframes via slideEmbedUrls below
    // "download_only" → show PPTX download link only (old behaviour)
    presentationMode: "google_slides" as "local_pdf" | "google_slides" | "download_only",

    // ── Day PDF Paths (used when presentationMode = "local_pdf") ─────────────
    dayPdfPaths: {
        1: "/slides/Day_1_Foundation.pdf",
        2: "/slides/Day_2_Prospecting.pdf",
        3: "/slides/Day_3_Discovery.pdf",
        4: "/slides/Day_4_Presentation.pdf",
        5: "/slides/Day_5_Objections.pdf",
        6: "/slides/Day_6_Mastery.pdf",
        7: "/slides/Day_7_Certification.pdf",
    } as Record<number, string>,

    // ── Google Slides Embed URLs (used when presentationMode = "google_slides") ─
    // Paste the full src URL from "File → Share → Publish to web → Embed"
    // e.g. "https://docs.google.com/presentation/d/YOUR_ID/embed"
    slideEmbedUrls: {
        1: "https://docs.google.com/presentation/d/e/2PACX-1vRsatlMJGF45s06W4Yhn4yVeY5GeYEVHSzeWjd7poSgAV7EcG21NBE_IcmM4mqEng/pubembed?start=false&loop=false&delayms=3000",  // Day 1
        2: "https://docs.google.com/presentation/d/e/2PACX-1vTyrsdR9Ufio881hvDwmfAYWKFaB56Y8tZlRRLsO3uFdEi8Thv7Z-yVIiSR7rQ1RQ/pubembed?start=false&loop=false&delayms=3000",  // Day 2
        3: "https://docs.google.com/presentation/d/e/2PACX-1vSALSQ9PqyTtwq5rYLf-qltZZHt1Heq-YAmK_ISJiFTqc-d50e8BiU2_IyQMjVvJQ/pubembed?start=false&loop=false&delayms=3000",  // Day 3
        4: "https://docs.google.com/presentation/d/e/2PACX-1vQoaA1NsVyM1UL0-7Ux-UFsNZ36ijrwvDC_h3EksVLPvKHO4JrPEQgOb3EKwBQgow/pubembed?start=false&loop=false&delayms=3000",  // Day 4
        5: "https://docs.google.com/presentation/d/e/2PACX-1vRk4ryjJEA54rk3z4f_5Cg5pWqaJjE6OrscJ2UX3eylP3CO0zNbPA6oRJ_bJzI8jA/pubembed?start=false&loop=false&delayms=3000",  // Day 5
        6: "https://docs.google.com/presentation/d/e/2PACX-1vQV6lrQYl0V9PKwzkpaTaRXIO7zCvZQiSO4IaXj3SMegqwY5nZ7xH6IWEG_9oghVg/pubembed?start=false&loop=false&delayms=3000",  // Day 6
        7: "https://docs.google.com/presentation/d/e/2PACX-1vS4CgjxfPSmE0AvcjsAdVfLkbZw8X_Y9TeD75QTVMd2eWybyleylzqw2j4xvKwhtA/pubembed?start=false&loop=false&delayms=3000",  // Day 7
    } as Record<number, string>,
} as const

// ── Module Slide Start Pages ─────────────────────────────────────────────────
// Auto-generated by extract_slide_modules.py — do not edit manually.
// Each value is the 1-indexed slide number where that module begins in the day PDF.
export const SLIDE_START_PAGES: Record<string, number> = {
    "mod_1_1": 1,
    "mod_1_2": 10,
    "mod_1_3": 15,
    "mod_1_4": 21,
    "mod_1_5": 28,
    "mod_1_6": 38,
    "mod_1_7": 44,
    "mod_1_8": 1,
    "mod_2_1": 1,
    "mod_2_2": 2,
    "mod_2_3": 2,
    "mod_2_4": 2,
    "mod_2_5": 2,
    "mod_2_6": 2,
    "mod_2_7": 2,
    "mod_2_8": 2,
    "mod_3_1": 1,
    "mod_3_2": 12,
    "mod_3_3": 22,
    "mod_3_4": 30,
    "mod_3_5": 39,
    "mod_3_6": 48,
    "mod_3_7": 55,
    "mod_3_8": 62,
    "mod_3_9": 67,
    "mod_4_1": 1,
    "mod_4_2": 12,
    "mod_4_3": 22,
    "mod_4_4": 32,
    "mod_4_5": 42,
    "mod_4_6": 51,
    "mod_4_7": 60,
    "mod_4_8": 69,
    "mod_4_9": 78,
    "mod_5_1": 1,
    "mod_5_2": 10,
    "mod_5_3": 18,
    "mod_5_4": 24,
    "mod_5_5": 30,
    "mod_5_6": 37,
    "mod_5_7": 43,
    "mod_5_8": 50,
    "mod_5_9": 56,
    "mod_5_10": 62,
    "mod_6_1": 1,
    "mod_6_2": 9,
    "mod_6_3": 18,
    "mod_6_4": 25,
    "mod_6_5": 31,
    "mod_6_6": 37,
    "mod_6_7": 43,
    "mod_6_8": 50,
    "mod_6_9": 56,
    "mod_7_1": 1,
    "mod_7_2": 8,
    "mod_7_3": 14,
    "mod_7_4": 19,
    "mod_7_5": 25,
    "mod_7_6": 30,
    "mod_7_8": 42,
    "mod_7_9": 48,
}
